### ISSUE TITLE
How to enhance existing document list/create new document list

### ISSUE THREAD

**Issue by adambezecny** [innodev-au/wmboost-data#1]
Hi,

My java service will have following interface:
		// --- <<IS-START(testBigIPSetup)>> ---
		// @sigtype java 3.5
		// [i] record:1:required gtm
		// [i] - field:0:required gtmDnsAlias
		// [i] - field:0:required targetDataCentre
		// [o] record:1:required gtm
		// [o] - field:0:required gtmDnsAlias
		// [o] - field:0:required gtmIP
		// [o] - field:0:required ltmDnsAlias
		// [o] - field:0:required ltmIP
		// [o] - field:0:required status

i.e. there will be multiple documents (document list) on output. I did see a section about nested documents (https://github.com/innodev-au/wmboost-data/wiki/Nested-Documents) which explains how to add single nested document. But how to add multiple documents with same name (gtm in my case)? Put mehod called like this (in cycle)
this.document.docEntry(ATTR_GTM).put(gtmDTO.getPipelineAsDocument());

simply replaces existing gtm item. I did not find any way how to insert multiple documents same as pub.document:insertDocument is doing? Is this supported? Please advise.

cheers,

Adam

**Comment by adambezecny** [comment]
one more fixe, interface will be like this
		// @sigtype java 3.5
		// [i] field:0:required targetDataCentre
		// [i] field:0:required environment
		// [o] record:1:required gtm
		// [o] - field:0:required gtmDnsAlias
		// [o] - field:0:required gtmIP
		// [o] - field:0:required ltmDnsAlias
		// [o] - field:0:required ltmIP
		// [o] - field:0:required status

**Comment by adambezecny** [comment]
Issue resolved! I found the answer in motivational example. When I put List<Document> into this.document.docsEntry(ATTR_GTM) it works!

**Comment by inno-juanal** [comment]
Hi Adam

I'm glad you've resolved it.

As a note, there's a subtle difference between a variable with a list of documents vs multiple variables with the same name, each holding a document. Refer to [https://github.com/innodev-au/wmboost-data/wiki/Unit-and-Split-Entries](https://github.com/innodev-au/wmboost-data/wiki/Unit-and-Split-Entries) for more info if you're interested. 

99% percent of the cases one wants a variable to hold a list of documents, which is what docsEntry is for.

Regards,
Juanal.
